# Generated by Django 5.1.3 on 2025-03-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(max_length=255, unique=True)),
                ('media_type', models.CharField(max_length=50)),
                ('media_url', models.URLField()),
                ('caption', models.TextField(blank=True, null=True)),
                ('permalink', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
