# Generated by Django 5.1.3 on 2025-03-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
