# Generated by Django 5.1.3 on 2025-03-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_winner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='image',
            field=models.ImageField(upload_to='winners/'),
        ),
    ]
