# Generated by Django 5.1.3 on 2025-03-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_winner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
    ]
